export const games = [
  // Classic games with Wikimedia URLs (these should work)
  { id: 1, title: "Flappy Bird", description: "Simple flying bird game.", image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Flappy_Bird_icon.png", embedUrl: "https://www.crazygames.com/embed/flappy-bird" },
  { id: 2, title: "2048", description: "Slide tiles to merge them.", image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/2048_Logo.png", embedUrl: "https://www.crazygames.com/embed/2048" },
  { id: 3, title: "Tetris", description: "Classic falling blocks puzzle.", image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tetris_logo.png", embedUrl: "https://www.crazygames.com/embed/tetris" },
  { id: 4, title: "Pac-Man", description: "Navigate the maze and eat dots.", image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pac-Man_Logo.png", embedUrl: "https://www.crazygames.com/embed/pac-man" },
  { id: 5, title: "Snake", description: "Control the snake to eat food.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Snake_game.png", embedUrl: "https://www.crazygames.com/embed/snake" },
  { id: 6, title: "Space Invaders", description: "Shoot aliens descending from above.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Space_invaders_logo.png", embedUrl: "https://www.crazygames.com/embed/space-invaders" },
  { id: 7, title: "Pong", description: "Bounce the ball past your opponent.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Pong_logo.png", embedUrl: "https://www.crazygames.com/embed/pong" },
  { id: 8, title: "Asteroids", description: "Destroy asteroids and avoid collisions.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Asteroids_logo.png", embedUrl: "https://www.crazygames.com/embed/asteroids" },
  { id: 9, title: "Breakout", description: "Bounce the ball to break bricks.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Breakout_logo.png", embedUrl: "https://www.crazygames.com/embed/breakout" },

  // HTML5 games with placeholder images - you'll need to update these
  { id: 10, title: "Red Ball", description: "Platformer with physics.", image: "https://via.placeholder.com/300x200/FF0000/FFFFFF?text=Red+Ball", embedUrl: "https://funhtml5games.com/red-ball/" },
  { id: 11, title: "Paper.io", description: "Expand your territory.", image: "https://via.placeholder.com/300x200/00FF00/FFFFFF?text=Paper.io", embedUrl: "https://funhtml5games.com/paper-io/" },
  { id: 12, title: "Vex 3", description: "Difficult platformer.", image: "https://via.placeholder.com/300x200/FF00FF/FFFFFF?text=Vex+3", embedUrl: "https://funhtml5games.com/vex-3/" },
  { id: 13, title: "Tank Trouble", description: "Tank battle for two players.", image: "https://via.placeholder.com/300x200/0000FF/FFFFFF?text=Tank+Trouble", embedUrl: "https://funhtml5games.com/tank-trouble/" },
  { id: 14, title: "Slope Racing", description: "Race down the slope.", image: "https://via.placeholder.com/300x200/FFFF00/000000?text=Slope+Racing", embedUrl: "https://funhtml5games.com/slope-racing/" },
  { id: 15, title: "Boxing Champs", description: "Arcade boxing game.", image: "https://via.placeholder.com/300x200/FF4500/FFFFFF?text=Boxing+Champs", embedUrl: "https://funhtml5games.com/boxing-champs/" },
  { id: 16, title: "Soccer Legends", description: "Arcade soccer game.", image: "https://via.placeholder.com/300x200/00FFFF/000000?text=Soccer+Legends", embedUrl: "https://funhtml5games.com/soccer-legends/" },
  { id: 17, title: "Fireboy and Watergirl", description: "Co-op puzzle platformer.", image: "https://via.placeholder.com/300x200/FF69B4/FFFFFF?text=Fireboy+Watergirl", embedUrl: "https://funhtml5games.com/fireboy-watergirl/" },
  { id: 18, title: "Slope Ball", description: "Endless ball running.", image: "https://via.placeholder.com/300x200/ADFF2F/000000?text=Slope+Ball", embedUrl: "https://funhtml5games.com/slope-ball/" },
  { id: 19, title: "Basketball Stars", description: "Arcade basketball game.", image: "https://via.placeholder.com/300x200/FFA500/FFFFFF?text=Basketball+Stars", embedUrl: "https://funhtml5games.com/basketball-stars/" },
  { id: 20, title: "Learn to Fly", description: "Control penguin and fly.", image: "https://via.placeholder.com/300x200/87CEEB/000000?text=Learn+to+Fly", embedUrl: "https://funhtml5games.com/learn-to-fly/" },
  { id: 21, title: "Slope 2", description: "Continue the slope adventure.", image: "https://via.placeholder.com/300x200/32CD32/FFFFFF?text=Slope+2", embedUrl: "https://funhtml5games.com/slope-2/" },
  { id: 22, title: "Red Ball 2", description: "More physics challenges.", image: "https://via.placeholder.com/300x200/DC143C/FFFFFF?text=Red+Ball+2", embedUrl: "https://funhtml5games.com/red-ball-2/" },
  { id: 23, title: "Paper.io 2", description: "Advanced territory game.", image: "https://via.placeholder.com/300x200/90EE90/000000?text=Paper.io+2", embedUrl: "https://funhtml5games.com/paper-io-2/" },
  { id: 24, title: "Vex 4", description: "New platformer challenges.", image: "https://via.placeholder.com/300x200/EE82EE/FFFFFF?text=Vex+4", embedUrl: "https://funhtml5games.com/vex-4/" },
  { id: 25, title: "Tank Trouble 2", description: "Tank battle continues.", image: "https://via.placeholder.com/300x200/4169E1/FFFFFF?text=Tank+Trouble+2", embedUrl: "https://funhtml5games.com/tank-trouble-2/" },
  { id: 26, title: "Slope Racing 2", description: "Even faster slopes.", image: "https://via.placeholder.com/300x200/DAA520/000000?text=Slope+Racing+2", embedUrl: "https://funhtml5games.com/slope-racing-2/" },
  { id: 27, title: "Boxing Champs 2", description: "More boxing fun.", image: "https://via.placeholder.com/300x200/FF6347/FFFFFF?text=Boxing+Champs+2", embedUrl: "https://funhtml5games.com/boxing-champs-2/" },
  { id: 28, title: "Soccer Legends 2", description: "New soccer challenges.", image: "https://via.placeholder.com/300x200/40E0D0/000000?text=Soccer+Legends+2", embedUrl: "https://funhtml5games.com/soccer-legends-2/" },
  { id: 29, title: "Fireboy and Watergirl 2", description: "New co-op puzzles.", image: "https://via.placeholder.com/300x200/FFB6C1/FFFFFF?text=Fireboy+Watergirl+2", embedUrl: "https://funhtml5games.com/fireboy-watergirl-2/" },
  { id: 30, title: "Slope Ball 2", description: "Even faster endless run.", image: "https://via.placeholder.com/300x200/7FFF00/000000?text=Slope+Ball+2", embedUrl: "https://funhtml5games.com/slope-ball-2/" },
  { id: 31, title: "Basketball Stars 2", description: "More arcade fun.", image: "https://via.placeholder.com/300x200/FF8C00/FFFFFF?text=Basketball+Stars+2", embedUrl: "https://funhtml5games.com/basketball-stars-2/" },
  { id: 32, title: "Learn to Fly 2", description: "New flying adventures.", image: "https://via.placeholder.com/300x200/4682B4/FFFFFF?text=Learn+to+Fly+2", embedUrl: "https://funhtml5games.com/learn-to-fly-2/" },
  { id: 33, title: "Red Ball 3", description: "Platforming continues.", image: "https://via.placeholder.com/300x200/B22222/FFFFFF?text=Red+Ball+3", embedUrl: "https://funhtml5games.com/red-ball-3/" },
  { id: 34, title: "Paper.io 3", description: "Territory domination.", image: "https://via.placeholder.com/300x200/98FB98/000000?text=Paper.io+3", embedUrl: "https://funhtml5games.com/paper-io-3/" },
  { id: 35, title: "Vex 5", description: "New platformer levels.", image: "https://via.placeholder.com/300x200/DDA0DD/FFFFFF?text=Vex+5", embedUrl: "https://funhtml5games.com/vex-5/" },
  { id: 36, title: "Tank Trouble 3", description: "More tank battles.", image: "https://via.placeholder.com/300x200/0000CD/FFFFFF?text=Tank+Trouble+3", embedUrl: "https://funhtml5games.com/tank-trouble-3/" },
  { id: 37, title: "Slope Racing 3", description: "Faster and challenging slopes.", image: "https://via.placeholder.com/300x200/B8860B/000000?text=Slope+Racing+3", embedUrl: "https://funhtml5games.com/slope-racing-3/" },
  { id: 38, title: "Boxing Champs 3", description: "Arcade boxing continues.", image: "https://via.placeholder.com/300x200/FF4500/FFFFFF?text=Boxing+Champs+3", embedUrl: "https://funhtml5games.com/boxing-champs-3/" },
  { id: 39, title: "Soccer Legends 3", description: "Exciting soccer matches.", image: "https://via.placeholder.com/300x200/48D1CC/000000?text=Soccer+Legends+3", embedUrl: "https://funhtml5games.com/soccer-legends-3/" },
  { id: 40, title: "Fireboy and Watergirl 3", description: "Puzzle adventures.", image: "https://via.placeholder.com/300x200/FFC0CB/FFFFFF?text=Fireboy+Watergirl+3", embedUrl: "https://funhtml5games.com/fireboy-watergirl-3/" },
  { id: 41, title: "Slope Ball 3", description: "Endless ball fun.", image: "https://via.placeholder.com/300x200/7CFC00/000000?text=Slope+Ball+3", embedUrl: "https://funhtml5games.com/slope-ball-3/" },
  { id: 42, title: "Basketball Stars 3", description: "Arcade basketball challenges.", image: "https://via.placeholder.com/300x200/FF7F50/FFFFFF?text=Basketball+Stars+3", embedUrl: "https://funhtml5games.com/basketball-stars-3/" },
  { id: 43, title: "Learn to Fly 3", description: "Fly new adventures.", image: "https://via.placeholder.com/300x200/4169E1/FFFFFF?text=Learn+to+Fly+3", embedUrl: "https://funhtml5games.com/learn-to-fly-3/" },
  { id: 44, title: "Red Ball 4", description: "New physics challenges.", image: "https://via.placeholder.com/300x200/A52A2A/FFFFFF?text=Red+Ball+4", embedUrl: "https://funhtml5games.com/red-ball-4/" },
  { id: 45, title: "Paper.io 4", description: "Territory game continues.", image: "https://via.placeholder.com/300x200/90EE90/000000?text=Paper.io+4", embedUrl: "https://funhtml5games.com/paper-io-4/" },
  { id: 46, title: "Vex 6", description: "More platformer levels.", image: "https://via.placeholder.com/300x200/DA70D6/FFFFFF?text=Vex+6", embedUrl: "https://funhtml5games.com/vex-6/" },
  { id: 47, title: "Tank Trouble 4", description: "Exciting tank battles.", image: "https://via.placeholder.com/300x200/191970/FFFFFF?text=Tank+Trouble+4", embedUrl: "https://funhtml5games.com/tank-trouble-4/" },
  { id: 48, title: "Slope Racing 4", description: "Even faster slopes.", image: "https://via.placeholder.com/300x200/CD853F/000000?text=Slope+Racing+4", embedUrl: "https://funhtml5games.com/slope-racing-4/" },
  { id: 49, title: "Boxing Champs 4", description: "More boxing fun.", image: "https://via.placeholder.com/300x200/FF1493/FFFFFF?text=Boxing+Champs+4", embedUrl: "https://funhtml5games.com/boxing-champs-4/" },
  { id: 50, title: "Soccer Legends 4", description: "New soccer challenges.", image: "https://via.placeholder.com/300x200/00CED1/000000?text=Soccer+Legends+4", embedUrl: "https://funhtml5games.com/soccer-legends-4/" }
];