export const games = [
  { id: 1, title: "Flappy Bird", description: "Simple flying bird game.", image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Flappy_Bird_icon.png", embedUrl: "https://www.crazygames.com/embed/flappy-bird" },
  { id: 2, title: "2048", description: "Slide tiles to merge them.", image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/2048_Logo.png", embedUrl: "https://www.crazygames.com/embed/2048" },
  { id: 3, title: "Tetris", description: "Classic falling blocks puzzle.", image: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tetris_logo.png", embedUrl: "https://www.crazygames.com/embed/tetris" },
  { id: 4, title: "Pac-Man", description: "Navigate the maze and eat dots.", image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pac-Man_Logo.png", embedUrl: "https://www.crazygames.com/embed/pac-man" },
  { id: 5, title: "Snake", description: "Control the snake to eat food.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Snake_game.png", embedUrl: "https://www.crazygames.com/embed/snake" },
  { id: 6, title: "Space Invaders", description: "Shoot aliens descending from above.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Space_invaders_logo.png", embedUrl: "https://www.crazygames.com/embed/space-invaders" },
  { id: 7, title: "Pong", description: "Bounce the ball past your opponent.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Pong_logo.png", embedUrl: "https://www.crazygames.com/embed/pong" },
  { id: 8, title: "Asteroids", description: "Destroy asteroids and avoid collisions.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Asteroids_logo.png", embedUrl: "https://www.crazygames.com/embed/asteroids" },
  { id: 9, title: "Breakout", description: "Bounce the ball to break bricks.", image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Breakout_logo.png", embedUrl: "https://www.crazygames.com/embed/breakout" },
  { id: 10, title: "Red Ball", description: "Platformer with physics.", image: "https://funhtml5games.com/images/games/red-ball.png", embedUrl: "https://funhtml5games.com/red-ball/" },
  { id: 11, title: "Paper.io", description: "Expand your territory.", image: "https://funhtml5games.com/images/games/paper-io.png", embedUrl: "https://funhtml5games.com/paper-io/" },
  { id: 12, title: "Vex 3", description: "Difficult platformer.", image: "https://funhtml5games.com/images/games/vex-3.png", embedUrl: "https://funhtml5games.com/vex-3/" },
  { id: 13, title: "Tank Trouble", description: "Tank battle for two players.", image: "https://funhtml5games.com/images/games/tank-trouble.png", embedUrl: "https://funhtml5games.com/tank-trouble/" },
  { id: 14, title: "Slope Racing", description: "Race down the slope.", image: "https://funhtml5games.com/images/games/slope-racing.png", embedUrl: "https://funhtml5games.com/slope-racing/" },
  { id: 15, title: "Boxing Champs", description: "Arcade boxing game.", image: "https://funhtml5games.com/images/games/boxing-champs.png", embedUrl: "https://funhtml5games.com/boxing-champs/" },
  { id: 16, title: "Soccer Legends", description: "Arcade soccer game.", image: "https://funhtml5games.com/images/games/soccer-legends.png", embedUrl: "https://funhtml5games.com/soccer-legends/" },
  { id: 17, title: "Fireboy and Watergirl", description: "Co-op puzzle platformer.", image: "https://funhtml5games.com/images/games/fireboy-watergirl.png", embedUrl: "https://funhtml5games.com/fireboy-watergirl/" },
  { id: 18, title: "Slope Ball", description: "Endless ball running.", image: "https://funhtml5games.com/images/games/slope-ball.png", embedUrl: "https://funhtml5games.com/slope-ball/" },
  { id: 19, title: "Basketball Stars", description: "Arcade basketball game.", image: "https://funhtml5games.com/images/games/basketball-stars.png", embedUrl: "https://funhtml5games.com/basketball-stars/" },
  { id: 20, title: "Learn to Fly", description: "Control penguin and fly.", image: "https://funhtml5games.com/images/games/learn-to-fly.png", embedUrl: "https://funhtml5games.com/learn-to-fly/" },
  { id: 21, title: "Slope 2", description: "Continue the slope adventure.", image: "https://funhtml5games.com/images/games/slope-2.png", embedUrl: "https://funhtml5games.com/slope-2/" },
  { id: 22, title: "Red Ball 2", description: "More physics challenges.", image: "https://funhtml5games.com/images/games/red-ball-2.png", embedUrl: "https://funhtml5games.com/red-ball-2/" },
  { id: 23, title: "Paper.io 2", description: "Advanced territory game.", image: "https://funhtml5games.com/images/games/paper-io-2.png", embedUrl: "https://funhtml5games.com/paper-io-2/" },
  { id: 24, title: "Vex 4", description: "New platformer challenges.", image: "https://funhtml5games.com/images/games/vex-4.png", embedUrl: "https://funhtml5games.com/vex-4/" },
  { id: 25, title: "Tank Trouble 2", description: "Tank battle continues.", image: "https://funhtml5games.com/images/games/tank-trouble-2.png", embedUrl: "https://funhtml5games.com/tank-trouble-2/" },
  { id: 26, title: "Slope Racing 2", description: "Even faster slopes.", image: "https://funhtml5games.com/images/games/slope-racing-2.png", embedUrl: "https://funhtml5games.com/slope-racing-2/" },
  { id: 27, title: "Boxing Champs 2", description: "More boxing fun.", image: "https://funhtml5games.com/images/games/boxing-champs-2.png", embedUrl: "https://funhtml5games.com/boxing-champs-2/" },
  { id: 28, title: "Soccer Legends 2", description: "New soccer challenges.", image: "https://funhtml5games.com/images/games/soccer-legends-2.png", embedUrl: "https://funhtml5games.com/soccer-legends-2/" },
  { id: 29, title: "Fireboy and Watergirl 2", description: "New co-op puzzles.", image: "https://funhtml5games.com/images/games/fireboy-watergirl-2.png", embedUrl: "https://funhtml5games.com/fireboy-watergirl-2/" },
  { id: 30, title: "Slope Ball 2", description: "Even faster endless run.", image: "https://funhtml5games.com/images/games/slope-ball-2.png", embedUrl: "https://funhtml5games.com/slope-ball-2/" },
  { id: 31, title: "Basketball Stars 2", description: "More arcade fun.", image: "https://funhtml5games.com/images/games/basketball-stars-2.png", embedUrl: "https://funhtml5games.com/basketball-stars-2/" },
  { id: 32, title: "Learn to Fly 2", description: "New flying adventures.", image: "https://funhtml5games.com/images/games/learn-to-fly-2.png", embedUrl: "https://funhtml5games.com/learn-to-fly-2/" },
  { id: 33, title: "Red Ball 3", description: "Platforming continues.", image: "https://funhtml5games.com/images/games/red-ball-3.png", embedUrl: "https://funhtml5games.com/red-ball-3/" },
  { id: 34, title: "Paper.io 3", description: "Territory domination.", image: "https://funhtml5games.com/images/games/paper-io-3.png", embedUrl: "https://funhtml5games.com/paper-io-3/" },
  { id: 35, title: "Vex 5", description: "New platformer levels.", image: "https://funhtml5games.com/images/games/vex-5.png", embedUrl: "https://funhtml5games.com/vex-5/" },
  { id: 36, title: "Tank Trouble 3", description: "More tank battles.", image: "https://funhtml5games.com/images/games/tank-trouble-3.png", embedUrl: "https://funhtml5games.com/tank-trouble-3/" },
  { id: 37, title: "Slope Racing 3", description: "Faster and challenging slopes.", image: "https://funhtml5games.com/images/games/slope-racing-3.png", embedUrl: "https://funhtml5games.com/slope-racing-3/" },
  { id: 38, title: "Boxing Champs 3", description: "Arcade boxing continues.", image: "https://funhtml5games.com/images/games/boxing-champs-3.png", embedUrl: "https://funhtml5games.com/boxing-champs-3/" },
  { id: 39, title: "Soccer Legends 3", description: "Exciting soccer matches.", image: "https://funhtml5games.com/images/games/soccer-legends-3.png", embedUrl: "https://funhtml5games.com/soccer-legends-3/" },
  { id: 40, title: "Fireboy and Watergirl 3", description: "Puzzle adventures.", image: "https://funhtml5games.com/images/games/fireboy-watergirl-3.png", embedUrl: "https://funhtml5games.com/fireboy-watergirl-3/" },
  { id: 41, title: "Slope Ball 3", description: "Endless ball fun.", image: "https://funhtml5games.com/images/games/slope-ball-3.png", embedUrl: "https://funhtml5games.com/slope-ball-3/" },
  { id: 42, title: "Basketball Stars 3", description: "Arcade basketball challenges.", image: "https://funhtml5games.com/images/games/basketball-stars-3.png", embedUrl: "https://funhtml5games.com/basketball-stars-3/" },
  { id: 43, title: "Learn to Fly 3", description: "Fly new adventures.", image: "https://funhtml5games.com/images/games/learn-to-fly-3.png", embedUrl: "https://funhtml5games.com/learn-to-fly-3/" },
  { id: 44, title: "Red Ball 4", description: "New physics challenges.", image: "https://funhtml5games.com/images/games/red-ball-4.png", embedUrl: "https://funhtml5games.com/red-ball-4/" },
  { id: 45, title: "Paper.io 4", description: "Territory game continues.", image: "https://funhtml5games.com/images/games/paper-io-4.png", embedUrl: "https://funhtml5games.com/paper-io-4/" },
  { id: 46, title: "Vex 6", description: "More platformer levels.", image: "https://funhtml5games.com/images/games/vex-6.png", embedUrl: "https://funhtml5games.com/vex-6/" },
  { id: 47, title: "Tank Trouble 4", description: "Exciting tank battles.", image: "https://funhtml5games.com/images/games/tank-trouble-4.png", embedUrl: "https://funhtml5games.com/tank-trouble-4/" },
  { id: 48, title: "Slope Racing 4", description: "Even faster slopes.", image: "https://funhtml5games.com/images/games/slope-racing-4.png", embedUrl: "https://funhtml5games.com/slope-racing-4/" },
  { id: 49, title: "Boxing Champs 4", description: "More boxing fun.", image: "https://funhtml5games.com/images/games/boxing-champs-4.png", embedUrl: "https://funhtml5games.com/boxing-champs-4/" },
  { id: 50, title: "Soccer Legends 4", description: "New soccer challenges.", image: "https://funhtml5games.com/images/games/soccer-legends-4.png", embedUrl: "https://funhtml5games.com/soccer-legends-4/" }
];
